print('|14|in_proj START D:/djpro/myapp1/migrations/0001_initial.py')
# Generated by Django 4.2.1 on 2023-05-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_autor', models.CharField(default='Unknown', max_length=50, verbose_name='Автор')),
                ('post_autor_photo', models.CharField(default='Unknown', max_length=250, verbose_name='Фото автора')),
                ('post_title', models.CharField(default='Unknown', max_length=250, verbose_name='Заголовок')),
                ('post_photo', models.CharField(default='Unknown', max_length=250, verbose_name='Картинка к статье')),
                ('post_category', models.CharField(default='Unknown', max_length=250, verbose_name='Категория')),
                ('post_full_text', models.TextField(default='Unknown', verbose_name='Статья')),
                ('post_date', models.DateTimeField(default='Unknown', verbose_name='Дата публикации')),
                ('post_viev', models.IntegerField(default='Unknown', verbose_name='Просмотры')),
                ('post_like', models.IntegerField(default='Unknown', verbose_name='Лайки')),
                ('post_comment', models.IntegerField(default='Unknown', verbose_name='Комментарии')),
                ('post_bookmark', models.IntegerField(default='Unknown', verbose_name='Закладки')),
            ],
        ),
    ]
print('|14|in_proj END D:/djpro/myapp1/migrations/0001_initial.py')
