print('|15|in_proj START D:/djpro/myapp1/migrations/0002_alter_articles_post_bookmark_and_more.py')
# Generated by Django 4.2.1 on 2023-05-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='post_bookmark',
            field=models.IntegerField(default=0, verbose_name='Закладки'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='post_comment',
            field=models.IntegerField(default=0, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='post_date',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='post_like',
            field=models.IntegerField(default=0, verbose_name='Лайки'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='post_viev',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
print('|15|in_proj END D:/djpro/myapp1/migrations/0002_alter_articles_post_bookmark_and_more.py')
