# Generated by Django 4.2.1 on 2023-07-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_alter_articles_post_bookmark_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=50, verbose_name='Name')),
                ('age', models.IntegerField(default=0, verbose_name='Age')),
            ],
        ),
    ]
